-- SQLite

DROP TABLE likes;

CREATE TABLE likes(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	filmId INTEGER NOT NULL,
	userId INTEGER NOT NULL,
	FOREIGN KEY(filmId) REFERENCES films(id)
	FOREIGN KEY(userId) REFERENCES users(id)
);

